

\connect tododb
/*CREATE TABLE IF NOT EXISTS assignee (
			 	ID 			INTEGER		PRIMARY KEY NOT NULL,
			 	NAME 		VARCHAR(25)	NOT NULL,
			 	LASTNAME 	VARCHAR(25)	NOT NULL
			 	);*/

CREATE TABLE IF NOT EXISTS tasks (
			 	ID 			SERIAL		PRIMARY KEY,
			 	NAME 		VARCHAR(25)	NOT NULL,
			 	PRIORITY 	INTEGER		NOT NULL,
			 	DESCRIPTION	VARCHAR(50),
			 	START_TIME	TIME		NOT NULL,
			 	END_TIME 	TIME		NOT NULL
			 	);
			 	--ASSIGNEE_ID	INTEGER,
			 	--FOREIGN KEY(ASSIGNEE_ID) REFERENCES assignee(ID)
			 	--);


